esphome:
  name: "heltec-test"

esp32:
  board: esp32-s3-devkitc-1
  framework:
    type: arduino

# Enable logging
logger:
#############################################################################

empty_component:
  id: empty_component_1
