esphome:
  name: "gpio-blink"
  #  includes:
  #    - my_custom_component.h
  libraries:
    - "FastLED"

esp32:
  board: esp32-s3-devkitc-1
  framework:
    type: arduino

##############################################################################
#external_components:
#  - source:
#    path: "../esphome"
#############################################################################

# Enable logging
logger:

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password

ota:
  password: !secret ota_password

# Enable Home Assistant API
api:
  encryption:
    key: !secret api_encryption_key

spi:
  clk_pin: GPIO9
  mosi_pin: GPIO10
  miso_pin: GPIO11

i2c:
  - id: bus_a
    sda: 17
    scl: 18
#  - id: bus_b
#    sda: 41
#    scl: 42

display:
  - platform: ssd1306_i2c
    model: "SSD1306 128x64"
    reset_pin: 21
    i2c_id: bus_a
    address: 0x3C
    lambda: |-
      it.fill(COLOR_ON);
      it.fill(COLOR_OFF);

gpio_blink:
#external_components:
#  - source: github://pr#4257
#    components: [fastled]
#    refresh: always

#light:
#  - platform: status_led
#    name: "Status LED"
#    pin: GPIO35
#- platform: fastled_clockless
#  chipset: WS2812B
#  pin: 7
#  num_leds: 10
#  rgb_order: GRB
#  name: "RGB Light"
