esphome:
  name: "heltec-wifi-lora-32-v3"

esp32:
  board: esp32-s3-devkitc-1
  framework:
    type: arduino

##############################################################################
#external_components:
#  - source:
#    path: "../esphome"
#############################################################################

# Enable logging
logger:

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password

ota:
  password: !secret ota_password

# Enable Home Assistant API
api:
  encryption:
    key: !secret api_encryption_key

i2c:
  - id: bus_a
    sda: 17
    scl: 18
#  - id: bus_b
#    sda: 41
#    scl: 42

display:
  - platform: ssd1306_i2c
    model: "SSD1306 128x64"
    reset_pin: 21
    i2c_id: bus_a
    address: 0x3C
    lambda: |-
      it.fill(COLOR_ON);
      it.fill(COLOR_OFF);
