esphome:
  name: "lora-receiver"
  includes:
  #  - my_lora_component.h
    - components/lora/receiver.h
  libraries:
    - "SPI"
    - "Ticker"
    - "SX126x-Arduino"

esp32:
  board: esp32-s3-devkitc-1
  framework:
    type: arduino

# Enable logging
logger:

#wifi:
#  networks:
#  - ssid: open_energy
#    password: CAFEF00D
    
#ota:
#  password: !secret ota_password

# Enable Home Assistant API
#api:
#  encryption:
#    key: !secret api_encryption_key

#spi:
#  clk_pin: GPIO9
#  mosi_pin: GPIO10
#  miso_pin: GPIO11

#i2c:
#  - id: bus_a
#    sda: 17
#    scl: 18

#############################################################################
custom_component:
  - lambda: |-
      auto my_custom = new MyCustomComponent();
      return {my_custom};
    components:
      - id: my_custom_id
