esphome:
  name: "lora-receiver"
  includes:
  #  - my_lora_component.h
    - components/lora/receiver.h
    # - components/lora/esphome_lora_version.h  
  libraries:
    - "SPI"
    - "Ticker"
    - "SX126x-Arduino"

esp32:
  board: esp32-s3-devkitc-1
  framework:
    type: arduino

packages:
  logger:     !include common/logger.yaml
  wifi:       !include common/wifi.yaml
  ota:        !include common/ota.yaml
  api:        !include common/api.yaml
  web_server: !include common/web_server.yaml
  status:     !include common/status.yaml
  
#############################################################################
#mqtt:
#  broker: 10.1.1.44
  # username: heltec-c7a8
  # password: "c7a8"

# Enable Home Assistant API
#api:
#  encryption:
#    key: API_ENCRYPTION_KEY

#spi:
#  clk_pin: GPIO9
#  mosi_pin: GPIO10
#  miso_pin: GPIO11

#i2c:
#  - id: bus_a
#    sda: 17
#    scl: 18

#############################################################################
custom_component:
  - lambda: |-
      auto my_custom = new MyCustomComponent();
      return {my_custom};
    components:
      - id: my_custom_id
